domain: mrinalsave.github.io
url: https://mrinalsave.github.io
baseurl: ""
title: my digital archive

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/devlog/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: blog
      permalink: /devlog/:year/:month/:day/:title.html

exclude:
  - node_modules
  - dist
  - vite.config.js
  - package.json
  - package-lock.json
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby